import gzip
configfile: 'config/config.yaml'


CALLSETS = config['callsets']
READS = config['reads']
PANGENIE = config['pangenie']
PANGENIE_MODULES = config['pangenie-modules']
DOWNSAMPLING = config['downsampling']

PANEL_SAMPLES = {}
for callset in CALLSETS.keys():
	for line in gzip.open(CALLSETS[callset]['multi'], 'rt'):
		if line.startswith("#CHROM"):
			PANEL_SAMPLES[callset] = line.strip().split()[9:]
			break



include: 'rules/leave-one-out.smk'

coverages = ['full'] + config['downsampling']
versions_to_run = [v for v in config['pangenie'].keys()] + [v for v in config['pangenie-modules'].keys()]


def leave_one_out_plots(wildcards):
	plots = []
	for callset in CALLSETS.keys():
		plots.extend( expand("{results}/leave-one-out/{callset}/plots/comparison-versions/{metric}/{metric}_{coverage}_{regions}.pdf", results=RESULTS_BENCH, callset=callset, metric=['concordance', 'precision-recall-typable', 'untyped', 'concordance-vs-untyped'], coverage=coverages, regions=['biallelic', 'multiallelic'] + [r for r in CALLSETS[callset]["regions"].keys()]))
		plots.extend( expand("{results}/leave-one-out/{callset}/plots/comparison-regions/{metric}/{metric}_{coverage}_{versions}.pdf", results=RESULTS_BENCH, callset=callset, metric=['concordance', 'precision-recall-typable', 'untyped'], coverage=coverages, versions=versions_to_run))
		plots.extend( expand("{results}/leave-one-out/{callset}/plots/comparison-coverages/{metric}/{metric}_{version}_{regions}.pdf", results=RESULTS_BENCH, callset=callset, metric=['concordance', 'precision-recall-typable', 'untyped'], version = versions_to_run, regions = ['biallelic', 'multiallelic'] + [r for r in CALLSETS[callset]["regions"].keys()]))
	return plots




rule all:
	input:
		leave_one_out_plots,
		expand("{results}/leave-one-out/{callset}/plots/resources/resources_{callset}-{coverage}.pdf", results = config['results'], callset = [c for c in config['callsets'].keys()], coverage = coverages),

rule leave_one_out:
	input:
		leave_one_out_plots,
		expand("{results}/leave-one-out/{callset}/plots/resources/resources_{callset}-{coverage}.pdf", results = config['results'], callset = [c for c in config['callsets'].keys()], coverage = coverages),
