configfile: "config/config.yaml"
include: "rules/construct-panel-pseudo-haplotypes.smk"

modes = []
if config["pangenie_multi_vcf"] != "":
	modes.append("multi")
if config["pangenie_bi_vcf"] != "":
	modes.append("bi")


rule all:
	input:
		expand("{outname}/panel/panel-multiallelic.vcf", outname = config["outname"]),
		expand("{outname}/panel/panel-biallelic.vcf", outname = config["outname"])
#		expand("results/statistics_{mode}.txt", mode = modes)
