# name of the output folder to which all results shall be written
results: "results"

### callsets to be used as input to PanGenie (multiple ones can be listed)

callsets:
 MC-hprc-chm13: # Minigraph-Cactus paper: MC calls for HPRC samples
  multi: "/gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/results/data/vcf/cactus-100000/cactus_filtered_ids.vcf.gz"
  bi: "/gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/results/data/vcf/cactus-100000/cactus_filtered_ids_biallelic.vcf.gz"
  reference: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/data/reference/chm13v2.0.fa"
  variants:
     - snp
     - indels
     - large-deletion
     - large-insertion
     - large-complex
  repeat_regions: "resources/chm13v2.0_RepeatMasker_4.1.2p1.2022Apr14.bed"
  leave_one_out_samples:
    - HG00438
    - HG00621
    - HG00673
    - HG00735
    - HG00741
    - HG01071
    - HG01106
    - HG01109
    - HG01123
    - HG01175
    - HG01243
    - HG01258
    - HG01358
    - HG01361
    - HG01891
    - HG01928
    - HG01952
    - HG01978
    - HG02055
    - HG02080
#    - HG02109 no reads in 1000G
    - HG02145
    - HG02148
    - HG02257
    - HG02486
    - HG02559
    - HG02572
    - HG02622
    - HG02630
    - HG02717
    - HG02723
    - HG02886
    - HG03098
    - HG03453
    - HG03486
    - HG03492
    - HG03516
    - HG03540
    - HG03579
    - NA18906
    - NA20129
    - NA21309


 MC-hgsvc3-freeze1-chm13-corrected-raw: # MC calls for freeze1 samples (corrected sex chromosomes, raw vcf)
   multi: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/prepare-vcf-MC/results-corrected-sex-chromosomes-raw/vcf/MC-hgsvc3-freeze1-chm13/MC-hgsvc3-freeze1-chm13_filtered_ids.vcf.gz"
   bi: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/prepare-vcf-MC/results-corrected-sex-chromosomes-raw/vcf/MC-hgsvc3-freeze1-chm13/MC-hgsvc3-freeze1-chm13_filtered_ids_biallelic.vcf.gz"
   reference: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/data/reference/chm13v2.0.fa"
   variants:
     - snp 
     - indels
     - large-deletion
     - large-insertion
     - large-complex
   repeat_regions: "resources/chm13v2.0_RepeatMasker_4.1.2p1.2022Apr14.bed"
   leave_one_out_samples:
     - HG00171
     - HG00268
     - HG00358
     - HG00731
#     - HG00732 data to be regenerated
     - HG00733
     - HG01114
     - HG01352
     - HG01457
     - HG01505
     - HG01573
     - HG01596
     - HG01890
     - HG02011
     - HG02018
     - HG02059
     - HG02106
     - HG02282
     - HG02492
     - HG02554
     - HG02587
     - HG02666
     - HG02769
     - HG02818
     - HG02953
     - HG03009
     - HG03065
     - HG03248
     - HG03371
     - HG03452
     - HG03456
     - HG03520
     - HG03683
     - HG03807
     - HG04036
     - HG04217
     - NA18534
     - NA18989
     - NA19036
     - NA19129
     - NA19317
     - NA19331
     - NA19347
     - NA19384
     - NA19434
     - NA19650
     - NA19705
     - NA19836
     - NA19983
     - NA20355
     - NA20509
     - NA20847
#     - NA21487 not part of 1000G reads
     - NA24385


 MC-hgsvc3-freeze1-hprc-chm13-corrected-raw: # MC calls for HPRC + freeze1 samples (corrected sex chromosomes + using raw vcf)
   multi: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/prepare-vcf-MC/results-corrected-sex-chromosomes-raw/vcf/MC-hgsvc3-freeze1-hprc-chm13/MC-hgsvc3-freeze1-hprc-chm13_filtered_ids.vcf.gz"
   bi: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/prepare-vcf-MC/results-corrected-sex-chromosomes-raw/vcf/MC-hgsvc3-freeze1-hprc-chm13/MC-hgsvc3-freeze1-hprc-chm13_filtered_ids_biallelic.vcf.gz"
   reference: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/data/reference/chm13v2.0.fa"
   variants:
     - snp 
     - indels
     - large-deletion
     - large-insertion
     - large-complex
   repeat_regions: "resources/chm13v2.0_RepeatMasker_4.1.2p1.2022Apr14.bed"
   leave_one_out_samples:
     - HG00171
     - HG00268
     - HG00358
     - HG00731
#     - HG00732 data to be regenerated
     - HG00733
     - HG01114
     - HG01352
     - HG01457
     - HG01505
     - HG01573
     - HG01596
     - HG01890
     - HG02011
     - HG02018
     - HG02059
     - HG02106
     - HG02282
     - HG02492
     - HG02554
     - HG02587
     - HG02666
     - HG02769
     - HG02818
     - HG02953
     - HG03009
     - HG03065
     - HG03248
     - HG03371
     - HG03452
     - HG03456
     - HG03520
     - HG03683
     - HG03807
     - HG04036
     - HG04217
     - NA18534
     - NA18989
     - NA19036
     - NA19129
     - NA19317
     - NA19331
     - NA19347
     - NA19384
     - NA19434
     - NA19650
     - NA19705
     - NA19836
     - NA19983
     - NA20355
     - NA20509
     - NA20847
#     - NA21487 not part of 1000G reads
     - NA24385

     - HG00438
     - HG00621
     - HG00673
     - HG00735
     - HG00741
     - HG01071
     - HG01106
     - HG01109
     - HG01123
     - HG01175
     - HG01243
     - HG01258
     - HG01358
     - HG01361
     - HG01891
     - HG01928
     - HG01952
     - HG01978
     - HG02055
     - HG02080
#     - HG02109 no reads in 1000G
     - HG02145
     - HG02148
     - HG02257
     - HG02486
     - HG02559
     - HG02572
     - HG02622
     - HG02630
     - HG02717
     - HG02723
     - HG02886
     - HG03098
     - HG03453
     - HG03486
     - HG03492
     - HG03516
     - HG03540
     - HG03579
     - NA18906
     - NA20129
     - NA21309


# read data. File required that specifies a sample name, path to FASTA/FASTQ data and superpopulation:
# FamilyID	SampleID	FatherID	MotherID	Population	Superpopulation	Sample_Illumina
reads: "resources/genotyping-pilot-reads.tsv"


# PanGenie command. Different versions can be run by listing several commandlines
pangenie: {}


# PanGenie command to be used for not yet released version of PanGenie (leave empty for now)
pangenie-modules:
 pangenie-109: "singularity exec --bind /:/hilbert eblerjana_eblerjana_pangenie-v3.0.3.sif PanGenie -a 109"


# Downsampling coverages for leave-one-out experiment. If reads shall not be downsampled, leave empty.
downsampling: []
