include: "rules/compute-sv-counts-collapse.smk"

rule all:
	input:
		expand("results/sv-count-comparison{regions}.pdf", regions = ["", "_annotated"] if config["regions"] else [""]),
		"results/length-distribution.pdf"
