configfile: "config/config.yaml"

GENOTYPED_SETS = config['callsets']
POPULATIONS = config['populations']


include: "rules/compute-sv-counts-collapse.smk"

rule all:
	input:
		expand("{results}/sv-count-comparison.pdf", results = config["results"]),
		expand("{results}/length-distribution.pdf", results = config["results"])
